Test package.json

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -20,11 +20,12 @@ if [ ! -d $SCALA_HOME ]; then
   exit 1
 fi
 
-
-$GRUNT_HOME/bin/compile $1 $2
-if [ "$?" != "0" ]; then
-  echo "grunt build failed :("
-  exit 1
+if [ -e "$0/package.json" ]; then
+  $GRUNT_HOME/bin/compile $1 $2
+  if [ "$?" != "0" ]; then
+    echo "grunt build failed :("
+    exit 1
+  fi
 fi
 
 $SCALA_HOME/bin/compile $1 $2
